### ISSUE TITLE
지난주 배포 코드리뷰 확인

### ISSUE THREAD

**Issue by crongro** [boostcamp-2020/Project18-D-WEB-Boostact#44]
수고하셨네요. 멋진시도 응원합니다.

라우터와 데모위주로 많이 구현된거 같은데, 리뷰남겨요.

https://github.com/boostcamp-2020/Project18-D-WEB-Boostact/pull/35#pullrequestreview-546061624

확인후 이슈 close해주세요

**Comment by simjaeik** [comment]
팀원들과 같이 리뷰 확인했습니다! 바쁜 일정에도 신경써주셔서 감사합니다 :)
말씀해주신 내용 반영하겠습니다!
